### ISSUE TITLE
pyhob installation problems on Ubuntu 16.04

### ISSUE THREAD

**Issue by dfki-bruce** [rock-simulation/pybob#11]
Dear Sir or Madam,

Hello!
I am a working student in DFKI and now meet a problem with pyhob installation problems on Ubuntu 16.04,
that is :
I  followed the right steps,but the terminal told me 
xzhen@ENTERN-STUD-U:~/project/mars-dev/pybob$ ./pybob.py buildconf path="https://github.com/rock-simulation/simulation-buildconf.git"
You must set a root directory where all repositories will be checked out and all packages will be installed
Enter root directory or nothing for ["/home/dfki.uni-bremen.de/xzhen/project/mars-dev"]:  

'''
You can specify the number of CORES you want to use when compiling packages.**
Enter number of CORES [8]):  8

Enter default build type (debug|release) [debug]:  debug

Enter default rock flavor (stable|master) [master]:  master

Enter branch of buildconf [default]:  default
The configuration is written to "../pybob/pybob.yml".

   **## Fetching "https://github.com/rock-simulation/simulation-buildconf.gitdefault" into /home/dfki.uni-bremen.de/xzhen/project/mars-dev/autoproj
Traceback (most recent call last):
  File "./pybob.py", line 356, in <module>
    globals()[sys.argv[1].replace("-", "_")+"_"]()
  File "./pybob.py", line 68, in buildconf_
    buildconf.updatePackageSets(cfg)
  File "/home/dfki.uni-bremen.de/xzhen/project/mars-dev/pybob/buildconf.py", line 440, in updatePackageSets
    with open(path+"manifest") as f:
IOError: [Errno 2] No such file or directory: '/home/dfki.uni-bremen.de/xzhen/project/mars-dev/autoproj/manifest'**
xzhen@ENTERN-STUD-U:~/project/mars-dev/pybob$ cd ..
xzhen@ENTERN-STUD-U:~/project/mars-dev$ ls
autoproj  env.sh  install  pybob
xzhen@ENTERN-STUD-U:~/project/mars-dev$ cd autoproj/
xzhen@ENTERN-STUD-U:~/project/mars-dev/autoproj$ ls
bob  remotes
'''
it seems that it cannot find the required files even though they are exist in the folders,
so could please tell me how to fix it?

many thanks!

**Comment by AlexanderFabisch** [comment]
The problem is that cloning the repository [here](https://github.com/rock-simulation/pybob/blob/master/buildconf.py#L513) fails silently. It tries to checkout the branch 'default' which does not exist.

**Comment by malter** [comment]
Alexander is right. By just hitting enter instead of typing "default", the default branch is used, which is mostly the "master" branch. I will change the prompt to ask explicitly for a branch or none if the default should be used.

**Comment by AlexanderFabisch** [comment]
Showing an error message would also be nice.
