### ISSUE TITLE
pybob.yml is corupt

### ISSUE THREAD

**Issue by bpoppinga** [rock-simulation/pybob#14]
autoprojEnv: false
buildconfAddress: https://github.com/rock-learning/bolero_buildconf.git
buildconfBranch: ''
defBuildType: debug
devDir: ECHO is on.
pyScriptDir: ECHO is on./pybob
rockFlavor: master

**Comment by AlexanderFabisch** [comment]
...only on Windows (10?), of course.

**Comment by AlexanderFabisch** [comment]
This is most likely an issue with BOLeRo's installation script:

```bash
DEV_DIR="$( cd "$( dirname "$0" )" && pwd )" # what is the output?

if [ -f /mingw64.exe ]; then  # should be true on windows, can you verify this?
  DEV_DIR="$(cmd //c echo $DEV_DIR)"  # what is the output?
fi
...

# create default config for bolero
...
echo "devDir: ${DEV_DIR}" >> pybob.yml
echo "pyScriptDir: ${DEV_DIR}/pybob" >> pybob.yml
```

**Comment by AlexanderFabisch** [comment]
@malter The installation instructions for MARS seem to work on Windows 10. The difference is that pybob.yml is generated by pybob in this case. Why did we write the pybob.yml in the bootstrap script of bolero? Can I change it?

**Comment by AlexanderFabisch** [comment]
@bpoppinga Can you say which packages are missing?

**Comment by malter** [comment]
We write the pybob.yml because we know which buildconf to pull and the user doesn't have to enter the git address.
I just tested the bootstrap script on Windows 10 with msys2 and it worked fine. What is the system configuration where the script fails?

**Comment by AlexanderFabisch** [comment]
But we could just run

    ./pybob.py buildconf path="https://github.com/rock-learning/bolero_buildconf.git"

right? Is there any drawback?

**Comment by malter** [comment]
We could do that, but then we would need the user interaction asking for the path, the default branches, and the buildconf branch. The default user doesn't have to know about that. If the user is more experienced and want to change the settings he doesn't need the bootstrap script and can install bolero directly with pybob or autoproj, having all the options.

**Comment by malter** [comment]
I still have no idea what went wrong here: `devDir: ECHO is on.`
What shell was used?
It looks like the following line went wrong:
`DEV_DIR="$( cd "$( dirname "$0" )" && pwd )" # what is the output?`
Maybe the script was executed with `sh bootstrap_bolero.sh` instead of `bash ...`  or directly `./bootstrap_bolero.sh`?

**Comment by malter** [comment]
Error could not be reproduced
