### ISSUE TITLE
env.sh should set PYTHONPATH

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-simulation/pybob#2]
In my case I had to add the line

    export PYTHONPATH="/home/dfki.uni-bremen.de/afabisch/Projekte/bolero-dev/install/lib/python2.7/site-packages":$PYTHONPATH

**Comment by malter** [comment]
I think this is due to the fact that bolero installs some python extensions?
We can add the path by default, it shouldn't influence other applications.

**Comment by AlexanderFabisch** [comment]
Yes, BOLeRo has a Python part. You seem to forget that on purpose. :)

**Comment by malter** [comment]
Done. I knew about the python part of BOLeRo, but i didn't knew that python is also installed locally.

**Comment by AlexanderFabisch** [comment]
Great, thanks!
