### ISSUE TITLE
Traceback during pybob.py execution

### ISSUE THREAD

**Issue by brean** [rock-simulation/pybob#26]
When I try to run the bootstrap-magic install script on ubuntu 20.04 from
`https://raw.githubusercontent.com/dfki-ric/bagel_wiki/master/bootstrap_magic.sh`

I am getting this traceback: 
```
Traceback (most recent call last):
  File "./pybob.py", line 71, in <module>
    osdeps.loadOsdeps(cfg)
  File "/bob-magic-dev/pybob/osdeps.py", line 154, in loadOsdeps
    if int(version().split("~")[1].split(".")[0]) >= 20:
IndexError: list index out of range
```

I run inside docker/I am using this Dockerfile for installation:
https://gist.github.com/brean/5b4117652bcb05d60216aace7d7f6ffd

**Comment by malter** [comment]
I just fixed it, while I was just updating the build system for Ubuntu 20.04. ;-)
Looks good now (builds and runs on a clean virtual machine). ;-)
By the way, I also updated the Ubuntu 18.04 and 20.04 binaries yesterday.
