### ISSUE TITLE
pybob's env.sh overwrites current settings

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-simulation/pybob#7]
this affects at least the LD_LIBRARY_PATH

**Comment by AlexanderFabisch** [comment]
my use case is that I want to use BOLeRo in ROS and it works when I source the env.sh of bolero before ROS' setup.bash but not the other way around

**Comment by malter** [comment]
Can you save the output of "export" to a file for both variants and check the difference with "diff"?
Maybe, the main difference is the order of the pathes in the LD_LIBRARY_PATH resulting in ROS using the wrong urdfdom library.
We should check if pybob can use the ROS installation of console_bridge and urdfdom in your case.
The "overwrite.yml" in the buildconf includes an ignore list, you can try to add the ROS packages there in your buildconf, to not install them via pybob.

**Comment by AlexanderFabisch** [comment]
I don't know if the problem is fixed now, but there was a commit that probably fixed this bug: https://github.com/rock-simulation/pybob/commit/b2b823960d40a05db821febb5cb77d82786885c3

In a very old env.sh I found the following error:

    export LD_LIBRARY_PATH="/home/afabisch/Projekte/bolero-dev/install/lib:/home/afabisch/Projekte/bolero-dev/install/lib/x86_64-linux-gnu:$DYLD_LIBRARY_PATH"

**Comment by malter** [comment]
Ok, that old bug should have produced problems. I close the issue for now.
