### ISSUE TITLE
Cython is not installed correctly?

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-simulation/pybob#9]
Cython is defined as an os dependency. It is installed with apt-get on Ubuntu but that does not work somehow. It would actually be better to install it with pip anyway. Is it possible? @malter

**Comment by malter** [comment]
I think, with autoproj it is also installed via apt-get and I try to keep pybob and autoproj as compatible as possible. Do you have an Idea what is going wrong?
We can change the install in pybob, but it would be great if somebody could adapt it for autoproj, too.

**Comment by AlexanderFabisch** [comment]
I think we can close this. It is installed from apt in the CI docker (https://github.com/rock-learning/bolero/blob/master/docker/Dockerfile_CI#L8) and that works for Ubuntu >16.04.
